#!/usr/bin/env bash
set -euo pipefail

DROPLET_IP="167.71.206.69"
REPO="https://github.com/seyvincent19-creator/quizmaster-app.git"
APP_DIR="/var/www/quizmaster"
DB_NAME="quizmaster"
DB_USER="quizmaster"
DB_PASS="$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
APP_KEY=""  # will be generated by artisan

echo "========================================="
echo " QuizMaster — Server Setup"
echo " IP: $DROPLET_IP"
echo "========================================="

# ─── System update ────────────────────────────────────────────────
echo "[1/10] Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get upgrade -y -qq

# ─── Nginx ────────────────────────────────────────────────────────
echo "[2/10] Installing Nginx..."
apt-get install -y -qq nginx

# ─── PHP 8.2 ──────────────────────────────────────────────────────
echo "[3/10] Installing PHP 8.2 + extensions..."
apt-get install -y -qq software-properties-common
add-apt-repository -y ppa:ondrej/php
apt-get update -qq
apt-get install -y -qq \
    php8.2-fpm php8.2-cli php8.2-mysql php8.2-mbstring \
    php8.2-xml php8.2-curl php8.2-zip php8.2-bcmath \
    php8.2-gd php8.2-intl unzip curl git

# ─── MySQL 8 ──────────────────────────────────────────────────────
echo "[4/10] Installing MySQL 8..."
apt-get install -y -qq mysql-server
systemctl start mysql
systemctl enable mysql

echo "  Creating database and user..."
mysql -u root <<MYSQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
MYSQL

# ─── Composer ─────────────────────────────────────────────────────
echo "[5/10] Installing Composer..."
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# ─── Node.js 20 ───────────────────────────────────────────────────
echo "[6/10] Installing Node.js 20..."
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y -qq nodejs

# ─── Clone repository ─────────────────────────────────────────────
echo "[7/10] Cloning repository..."
mkdir -p /var/www
if [ -d "$APP_DIR" ]; then
    rm -rf "$APP_DIR"
fi
git clone "$REPO" "$APP_DIR"

# ─── Laravel backend setup ────────────────────────────────────────
echo "[8/10] Setting up Laravel backend..."
cd "$APP_DIR/quizmaster-backend"

composer install --no-dev --optimize-autoloader --quiet

cat > .env <<ENV
APP_NAME=QuizMaster
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://${DROPLET_IP}:8000

APP_LOCALE=en
APP_FALLBACK_LOCALE=en

LOG_CHANNEL=stack
LOG_STACK=single
LOG_LEVEL=error

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASS}

SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

CACHE_STORE=file
QUEUE_CONNECTION=sync
FILESYSTEM_DISK=local

SANCTUM_STATEFUL_DOMAINS=${DROPLET_IP}

MAIL_MAILER=log
MAIL_FROM_ADDRESS="noreply@quizmaster.com"
MAIL_FROM_NAME="QuizMaster"
ENV

php artisan key:generate --force
php artisan migrate --seed --force
php artisan config:cache
php artisan route:cache
php artisan view:cache

# Fix permissions
chown -R www-data:www-data "$APP_DIR/quizmaster-backend/storage"
chown -R www-data:www-data "$APP_DIR/quizmaster-backend/bootstrap/cache"
chmod -R 775 "$APP_DIR/quizmaster-backend/storage"
chmod -R 775 "$APP_DIR/quizmaster-backend/bootstrap/cache"

# ─── React frontend build ─────────────────────────────────────────
echo "[9/10] Building React frontend..."
cd "$APP_DIR/quizmaster-frontend"

VITE_API_URL="http://${DROPLET_IP}:8000/api" npm install --silent
VITE_API_URL="http://${DROPLET_IP}:8000/api" npm run build

# ─── Nginx configuration ──────────────────────────────────────────
echo "[10/10] Configuring Nginx..."

cp "$APP_DIR/deploy/nginx-frontend.conf" /etc/nginx/sites-available/quizmaster-frontend
cp "$APP_DIR/deploy/nginx-backend.conf"  /etc/nginx/sites-available/quizmaster-backend

ln -sf /etc/nginx/sites-available/quizmaster-frontend /etc/nginx/sites-enabled/quizmaster-frontend
ln -sf /etc/nginx/sites-available/quizmaster-backend  /etc/nginx/sites-enabled/quizmaster-backend

# Remove default site
rm -f /etc/nginx/sites-enabled/default

nginx -t
systemctl reload nginx

# ─── Firewall ─────────────────────────────────────────────────────
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 8000/tcp
ufw --force enable

echo ""
echo "========================================="
echo " Deployment complete!"
echo "========================================="
echo " Frontend : http://${DROPLET_IP}"
echo " Backend  : http://${DROPLET_IP}:8000/api"
echo " DB Pass  : ${DB_PASS}"
echo ""
echo " Health check: curl http://${DROPLET_IP}:8000/up"
echo "========================================="
